# Site settings
title: Harsh Tomar
description: Jekyll Theme Minimal Resume
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://htomar.xyz"

# User settings
username: Harsh Tomar
user_description: ./hello
user_title: Data Scientist
email: harshtomar.code@gmail.com
twitter_username: HashMortar
linkedin_username: tomarharsh
github_username:  harshtomarcode

exclude: ['package.json', 'src' , 'node_modules']
